apiVersion: "app.redislabs.com/v1"
kind: "RedisEnterpriseCluster"
metadata:
  name: "rec"
spec:
  nodes: 1
  uiServiceType: ClusterIP
  username: testuser@email.com
  redisEnterpriseNodeResources:
    limits:
      cpu: "2"
      memory: "4Gi"
    requests:
      cpu: "2"
      memory: "4Gi"
  persistentSpec:
      enabled: false
